version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nodejs
    container_name: nodejs
    ports:
      - "3333:3333"
    volumes:
      - ./:/usr/src/app
  cardapio-io-database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cardapio-io
    ports:
      - "15432:5432"
    volumes:
      - ./src/database/postgres:/var/lib/postgresql/data 